# Generated by Django 5.0.1 on 2025-03-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantryitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='url',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, help_text='Measurement unit (e.g., grams, cups, lb, oz)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity used in the recipe', max_digits=6),
        ),
    ]
