# Generated by Django 5.0.1 on 2025-03-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_contains_gluten_ingredient_is_dairy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_keto_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_nut_free',
            field=models.BooleanField(default=True),
        ),
    ]
