# Generated by Django 5.0.1 on 2025-04-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_dietary_tags_review'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='recipes.recipe'),
        ),
    ]
