import os
import django

# Set up the Django environment
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "backend.settings")
django.setup()

from recipes.models import Ingredient

# List of ingredients to add (each ingredient as a string)
ingredients_list = [
    "Acorn squash",
    "Active dry yeast",
    "Aged balsamic vinegar",
    "All‑purpose baking mix",
    "All‑purpose flour",
    "Allspice",
    "Almond",
    "Almond butter",
    "Almond extract",
    "Almond flour",
    "Almond milk",
    "Apple",
    "Apple cider vinegar",
    "Apple juice",
    "Applesauce",
    "Apricot",
    "Apricot preserves",
    "Artichoke hearts",
    "Arugula",
    "Asparagus",
    "Avocado",
    "Avocado oil",
    "Bacon",
    "Baking powder",
    "Baking soda",
    "Banana",
    "Barbecue sauce",
    "Balsamic vinegar",
    "Bay leaf",
    "Beef",
    "Beef broth",
    "Beef stock",
    "Bell pepper",
    "Basil",
    "Barley",
    "Black beans",
    "Black olives",
    "Black pepper",
    "Black peppercorns",
    "Blueberries",
    "Bread",
    "Bread crumbs",
    "Brown rice",
    "Brown sugar",
    "Brussels sprouts",
    "Butter",
    "Buttermilk",
    "Cabbage",
    "Cantaloupe",
    "Capers",
    "Carrot",
    "Carrots",
    "Cardamom",
    "Cayenne pepper",
    "Celery",
    "Celery seed",
    "Chili flakes",
    "Chili powder",
    "Chili sauce",
    "Chocolate",
    "Chocolate chips",
    "Cinnamon",
    "Cloves",
    "Cocoa powder",
    "Coconut",
    "Coconut cream",
    "Coconut milk",
    "Coconut oil",
    "Couscous",
    "Corn",
    "Cornmeal",
    "Corn syrup",
    "Cornstarch",
    "Cumin",
    "Curry powder",
    "Cucumber",
    "Dijon mustard",
    "Dill",
    "Egg(s)",
    "Evaporated milk",
    "Fennel seeds",
    "Feta cheese",
    "Fish sauce",
    "Flour",
    "Garlic",
    "Garlic powder",
    "Ginger",
    "Ginger ale",
    "Gouda cheese",
    "Granulated sugar",
    "Greek yogurt",
    "Hazelnuts",
    "Heavy cream",
    "Honey",
    "Jalapeño",
    "Kidney beans",
    "Ketchup",
    "Lentils",
    "Lemon",
    "Lemon juice",
    "Lemon zest",
    "Lettuce",
    "Lime",
    "Lime juice",
    "Lime zest",
    "Maple syrup",
    "Margarine",
    "Mayonnaise",
    "Milk",
    "Mint (fresh)",
    "Mozzarella cheese",
    "Mushrooms",
    "Mustard",
    "Mustard seeds",
    "Nutmeg",
    "Oats",
    "Oatmeal",
    "Olive oil",
    "Onion",
    "Orange",
    "Orange juice",
    "Oregano",
    "Parsley",
    "Parmesan cheese",
    "Paprika",
    "Pasta",
    "Peanut butter",
    "Peanut oil",
    "Pecans",
    "Pecorino cheese",
    "Peas",
    "Pinto beans",
    "Pork",
    "Potato",
    "Potatoes",
    "Powdered sugar",
    "Pesto",
    "Provolone cheese",
    "Quinoa",
    "Rice",
    "Rice flour",
    "Rice vinegar",
    "Red bell pepper",
    "Red onion",
    "Red wine",
    "Red wine vinegar",
    "Rice",  # Duplicate entry, you may remove duplicates.
    "Rosemary",
    "Raisins",
    "Sage",
    "Salt",
    "Scallions",
    "Shallots",
    "Sesame oil",
    "Sesame seeds",
    "Shrimp",
    "Salmon",
    "Soy sauce",
    "Spinach",
    "Squash (e.g. acorn squash)",
    "Sugar",
    "Sunflower oil",
    "Sweet potatoes",
    "Swiss cheese",
    "Tilapia",
    "Tofu",
    "Tuna",
    "Turmeric",
    "Thyme",
    "Tomato",
    "Tomato paste",
    "Tomato sauce",
    "Vanilla",
    "Vanilla extract",
    "Vanilla pudding",
    "Vegetable broth",
    "Vegetable oil",
    "Vinegar (general)",
    "White wine vinegar",
    "White rice",
    "White sugar",
    "White wine",
    "Walnuts",
    "Yeast",
    "Zucchini",
]

for name in ingredients_list:
    # Create or get the ingredient; unit and description are omitted.
    ingredient, created = Ingredient.objects.get_or_create(name=name)
    if created:
        print(f"Created: {name}")
    else:
        print(f"Exists: {name}")
